### ISSUE TITLE
different sizes and colors?

### ISSUE THREAD

**Issue by slager** [liannesheppard/ENVH556_2021course#10]
I thought this graph was a little bit confusing -- having two different aesthetics with two different scales that are actually just saying the same thing.  Is it better to just pick 1?

Note that PR #9  includes a fix to make it actually use log scale to generate colors, but this issue is about the broader question about whether to use both at all

https://github.com/liannesheppard/ENVH556_2021course/blob/d29fdef62f96fc058340388238ee8e236be48f1c/Week8LabGeostatistics.Rmd#L468

**Comment by slager** [comment]
Note that PR #9 also includes a fix to make it actually use log scale to generate colors, but this issue is about the broader question about whether to use both at all

**Comment by liannesheppard** [comment]
I had the two different scales and then I decided it was confusing so I decided to drop the different scales and just show the native scale.  Obviously I forgot to change the comment too.  I'll probably go ahead and accept the commit (though I could as easily reject it) since I need to make at least one more change anyways.

**Comment by slager** [comment]
Ah, yeah, that makes sense.
